export enum EnvEnum {
  mode = 'AI_TESTING_TOOL_MODE',
  fallback = 'AI_TESTING_TOOL_FALLBACK',
  debug = 'AI_TESTING_TOOL_DEBUG',
  projectKey = 'AI_TESTING_TOOL_PROJECT_KEY',
  launchName = 'AI_TESTING_TOOL_LAUNCH_NAME',
  planId = 'AI_TESTING_TOOL_PLAN_ID',
  planKey = 'AI_TESTING_TOOL_PLAN_KEY',
  planName = 'AI_TESTING_TOOL_PLAN_NAME',
  fixVersion = 'AI_TESTING_TOOL_FIX_VERSION',
  sprintName = 'AI_TESTING_TOOL_SPRINT',
}

export enum EnvIngestEnum {
  url = 'AI_TESTING_TOOL_INGEST_URL',
  token = 'AI_TESTING_TOOL_INGEST_TOKEN',
  timeoutMs = 'AI_TESTING_TOOL_INGEST_TIMEOUT_MS',
  completeTimeoutMs = 'AI_TESTING_TOOL_INGEST_COMPLETE_TIMEOUT_MS',
  maxPayloadBytes = 'AI_TESTING_TOOL_INGEST_MAX_PAYLOAD_BYTES',
  chunkThresholdBytes = 'AI_TESTING_TOOL_INGEST_CHUNK_THRESHOLD_BYTES',
  chunkMaxBytes = 'AI_TESTING_TOOL_INGEST_CHUNK_MAX_BYTES',
  maxRetries = 'AI_TESTING_TOOL_INGEST_MAX_RETRIES',
  retryBaseDelayMs = 'AI_TESTING_TOOL_INGEST_RETRY_BASE_DELAY_MS',
}

export enum EnvFileEnum {
  path = 'AI_TESTING_TOOL_FILE_PATH',
}
